const router = require('express').Router();
const swaggerUi = require('swagger-ui-express');

// PT: Arquivo gerado por "npm run swagger". Se nao existir, o servidor
//     nao sobe. Rode o comando antes de iniciar.
// EN: File generated by "npm run swagger". If it does not exist the server
//     will not start. Run that command first.
const swaggerDocument = require('../swagger-output.json');

// PT: A GUI interativa exigida pelo projeto fica em /api-docs.
// EN: The interactive GUI required by the project lives at /api-docs.
router.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));

router.get('/', (req, res) => {
  // #swagger.ignore = true
  res.send('CSE 341 - Movies API. Interactive documentation at /api-docs');
});

router.use('/movies', require('./movies'));
router.use('/genres', require('./genres'));

module.exports = router;
